{{- $fullName := include "density.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: density-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "density.name" . }}
    helm.sh/chart: {{ include "density.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  tls:
  # encrypted and stored in the kubernetes secrets registry
    - secretName: density-cert-registry-name-goes-here
      hosts:
        - {{ .Values.hostname}}.density.io
  rules:
  - host: {{ .Values.hostname}}.density.io
    http:
      paths:
      - path: /jobs
        backend:
          serviceName: "{{ .Release.Name }}-frontend-svc"
          servicePort: 80
      - path: /auth
        backend:
          serviceName: "{{ .Release.Name }}-backend-svc"
          servicePort: 80